version: 2.1

commands:
  test_frontend:
    steps:
      - checkout
      - run:
          name: Install relevant packages for frontend
          command: npm --prefix ./frontend install
      - run:
          name: Run unit tests for frontend
          command: npm --prefix ./frontend test

executors:
  docker-executor-node:
    docker:
      - image: circleci/node

jobs:
  setup_frontend:
    executor: docker-executor-node
    steps:
      - test_frontend

workflows:
  setup_frontend:
    jobs:
      - setup_frontend
